//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphDesigner.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GraphDesigner.Languages.Translation", typeof(Translation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutS {
            get {
                return ResourceManager.GetString("AboutS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string AcceptS {
            get {
                return ResourceManager.GetString("AcceptS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add item.
        /// </summary>
        internal static string addBoxS {
            get {
                return ResourceManager.GetString("addBoxS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add edge.
        /// </summary>
        internal static string addEdgeS {
            get {
                return ResourceManager.GetString("addEdgeS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add node.
        /// </summary>
        internal static string addNodeS {
            get {
                return ResourceManager.GetString("addNodeS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete item.
        /// </summary>
        internal static string deleteBoxS {
            get {
                return ResourceManager.GetString("deleteBoxS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete edge.
        /// </summary>
        internal static string deleteEdgeS {
            get {
                return ResourceManager.GetString("deleteEdgeS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete node.
        /// </summary>
        internal static string deleteNodeS {
            get {
                return ResourceManager.GetString("deleteNodeS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edge color.
        /// </summary>
        internal static string edgeColorS {
            get {
                return ResourceManager.GetString("edgeColorS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string EnglishS {
            get {
                return ResourceManager.GetString("EnglishS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string ExitS {
            get {
                return ResourceManager.GetString("ExitS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string FileS {
            get {
                return ResourceManager.GetString("FileS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find short path.
        /// </summary>
        internal static string findShortPathS {
            get {
                return ResourceManager.GetString("findShortPathS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string HelpS {
            get {
                return ResourceManager.GetString("HelpS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph was not loaded. Error!.
        /// </summary>
        internal static string InfoFailLoadS {
            get {
                return ResourceManager.GetString("InfoFailLoadS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph was not saved. Error!.
        /// </summary>
        internal static string InfoFailSaveS {
            get {
                return ResourceManager.GetString("InfoFailSaveS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information:.
        /// </summary>
        internal static string InfoLabelS {
            get {
                return ResourceManager.GetString("InfoLabelS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph loaded!.
        /// </summary>
        internal static string InfoSuccessLoadS {
            get {
                return ResourceManager.GetString("InfoSuccessLoadS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph saved!.
        /// </summary>
        internal static string InfoSuccessSaveS {
            get {
                return ResourceManager.GetString("InfoSuccessSaveS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every button have a tool tip on it!.
        /// </summary>
        internal static string InfoTextDefaultS {
            get {
                return ResourceManager.GetString("InfoTextDefaultS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string LanguageS {
            get {
                return ResourceManager.GetString("LanguageS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load from DB.
        /// </summary>
        internal static string loadFromDBS {
            get {
                return ResourceManager.GetString("loadFromDBS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load from file.
        /// </summary>
        internal static string loadFromFileS {
            get {
                return ResourceManager.GetString("loadFromFileS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string NewS {
            get {
                return ResourceManager.GetString("NewS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node color.
        /// </summary>
        internal static string nodeColorS {
            get {
                return ResourceManager.GetString("nodeColorS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node selection color.
        /// </summary>
        internal static string nodeSelectedColorS {
            get {
                return ResourceManager.GetString("nodeSelectedColorS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click two nodes one by one and new edge will appear!.
        /// </summary>
        internal static string notaddEdgeS {
            get {
                return ResourceManager.GetString("notaddEdgeS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on empty place on PaintBox to add new node.
        /// </summary>
        internal static string notaddNodeS {
            get {
                return ResourceManager.GetString("notaddNodeS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click item to delete it..
        /// </summary>
        internal static string notdeleteEdgeS {
            get {
                return ResourceManager.GetString("notdeleteEdgeS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click item to delete it..
        /// </summary>
        internal static string notdeleteNodeS {
            get {
                return ResourceManager.GetString("notdeleteNodeS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click two nodes one by one and shortest path will appear!.
        /// </summary>
        internal static string notfindShortPathS {
            get {
                return ResourceManager.GetString("notfindShortPathS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This string will help you! Look here from time to time..
        /// </summary>
        internal static string notInfoStringS {
            get {
                return ResourceManager.GetString("notInfoStringS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string OpenS {
            get {
                return ResourceManager.GetString("OpenS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string OptionsS {
            get {
                return ResourceManager.GetString("OptionsS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path do not exist.
        /// </summary>
        internal static string PathNotExistS {
            get {
                return ResourceManager.GetString("PathNotExistS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        internal static string RussianS {
            get {
                return ResourceManager.GetString("RussianS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveS {
            get {
                return ResourceManager.GetString("SaveS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to DB.
        /// </summary>
        internal static string saveToDBS {
            get {
                return ResourceManager.GetString("saveToDBS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to file.
        /// </summary>
        internal static string saveToFileS {
            get {
                return ResourceManager.GetString("saveToFileS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short path edge color.
        /// </summary>
        internal static string shortEdgeColorS {
            get {
                return ResourceManager.GetString("shortEdgeColorS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short path node color.
        /// </summary>
        internal static string shortNodeColorS {
            get {
                return ResourceManager.GetString("shortNodeColorS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string ToolsS {
            get {
                return ResourceManager.GetString("ToolsS", resourceCulture);
            }
        }
    }
}
